// Auto-generated by sanitizeGeneratedFiles
export async function onRequest(context) {
  try {
    const templates = [
      { id: 1, name: "Professional", description: "A clean, professional template" },
      { id: 2, name: "Creative", description: "A colorful, creative template" },
    ];
    return new Response(JSON.stringify(templates), {
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response("Error fetching templates", { status: 500 });
  }
}

export async function onRequest(context) {
  const { request } = context;
  try {
    const data = await request.json();
    const { userId, resumeData } = data;
    const savedResume = {
      userId,
      resumeId: new Date().getTime(),
      ...resumeData,
    };
    return new Response(JSON.stringify(savedResume), {
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response("Error saving resume", { status: 500 });
  }
}

export async function onRequest(context) {
  const { request } = context;
  try {
    const url = new URL(request.url);
    const userId = url.searchParams.get("userId");
    const userResumes = [
      { resumeId: 1, title: "Resume 1", userId },
      { resumeId: 2, title: "Resume 2", userId },
    ];
    return new Response(JSON.stringify(userResumes), {
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response("Error fetching user resumes", { status: 500 });
  }
}